package it.lsoft.haccp;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CarteFedeltaDesign extends VerticalLayout {
	protected TextField cardNumber;
	protected TextField point;
	protected Button btnAddPoint;
	protected Button btnGift;
	protected TextField saldo;
	protected Button btnPrint;
<<<<<<< HEAD
	protected Button btnPrintCard;
=======
>>>>>>> branch 'develop' of https://github.com/thiasos/HACCP.git
	protected Table table;

	public CarteFedeltaDesign() {
		Design.read(this);
	}
}
