package it.lsoft.haccp;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Table;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FornitoriDesign extends VerticalLayout {
	protected HorizontalLayout toolbar;
	protected Button newButton;
	protected Button editButton;
	protected Button deleteButton;
	protected TextField searchField;
	protected Table tableFornitori;
	protected FormLayout form;
	protected TextField nome;
	protected TextField indirizzo;
	protected TextField telefono;
	protected Button btnSave;
	protected Button btnAbort;

	public FornitoriDesign() {
		Design.read(this);
	}
}
